//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto.School.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auto.School.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating for car was successfully added.
        /// </summary>
        internal static string AddCarRating {
            get {
                return ResourceManager.GetString("AddCarRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rating for instructor&apos;s car.
        /// </summary>
        internal static string AddCarRating_CarRatingLabel {
            get {
                return ResourceManager.GetString("AddCarRating_CarRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rating for car from 1 to 5.
        /// </summary>
        internal static string AddCarRating_RatingLabel {
            get {
                return ResourceManager.GetString("AddCarRating_RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string AddCarRating_SubmitButton {
            get {
                return ResourceManager.GetString("AddCarRating_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AddReview_CancelButton {
            get {
                return ResourceManager.GetString("AddReview_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Rating.
        /// </summary>
        internal static string AddReview_CurrentRating {
            get {
                return ResourceManager.GetString("AddReview_CurrentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rating for instructor from 1 to 5.
        /// </summary>
        internal static string AddReview_RatingLabel {
            get {
                return ResourceManager.GetString("AddReview_RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write what you think about instructor.
        /// </summary>
        internal static string AddReview_ReviewLabel {
            get {
                return ResourceManager.GetString("AddReview_ReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your review here.
        /// </summary>
        internal static string AddReview_ReviewPlaceholder {
            get {
                return ResourceManager.GetString("AddReview_ReviewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review.
        /// </summary>
        internal static string AddReview_SubmitButton {
            get {
                return ResourceManager.GetString("AddReview_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review about instructor.
        /// </summary>
        internal static string AddReview_Title {
            get {
                return ResourceManager.GetString("AddReview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You review about instructor was successfully added.
        /// </summary>
        internal static string AddReviewSuccessResult {
            get {
                return ResourceManager.GetString("AddReviewSuccessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My chats.
        /// </summary>
        internal static string AllChats_MyChats {
            get {
                return ResourceManager.GetString("AllChats_MyChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start chatting.
        /// </summary>
        internal static string AllChats_NoMessages {
            get {
                return ResourceManager.GetString("AllChats_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open chat.
        /// </summary>
        internal static string AllChats_OpenChat {
            get {
                return ResourceManager.GetString("AllChats_OpenChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open details.
        /// </summary>
        internal static string AllInstructors_DetailsButton {
            get {
                return ResourceManager.GetString("AllInstructors_DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor has maximum number of students.
        /// </summary>
        internal static string AllInstructors_NotAvailale {
            get {
                return ResourceManager.GetString("AllInstructors_NotAvailale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Instructors.
        /// </summary>
        internal static string AllInstructors_Title {
            get {
                return ResourceManager.GetString("AllInstructors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string BirthdayDate {
            get {
                return ResourceManager.GetString("BirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Chat_Loading {
            get {
                return ResourceManager.GetString("Chat_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages in chat.
        /// </summary>
        internal static string Chat_NoMessages {
            get {
                return ResourceManager.GetString("Chat_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message.
        /// </summary>
        internal static string Chat_Placeholder {
            get {
                return ResourceManager.GetString("Chat_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Chat_Send {
            get {
                return ResourceManager.GetString("Chat_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recivier:.
        /// </summary>
        internal static string Chat_TitleLabel {
            get {
                return ResourceManager.GetString("Chat_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Chat_ToBottom {
            get {
                return ResourceManager.GetString("Chat_ToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string DrivingSkills_CloseButton {
            get {
                return ResourceManager.GetString("DrivingSkills_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DrivingSkills_Completed {
            get {
                return ResourceManager.GetString("DrivingSkills_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark completed.
        /// </summary>
        internal static string DrivingSkills_MarkCompleted {
            get {
                return ResourceManager.GetString("DrivingSkills_MarkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving skills to learn.
        /// </summary>
        internal static string DrivingSkills_Title {
            get {
                return ResourceManager.GetString("DrivingSkills_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get instructor instance. Try again later.
        /// </summary>
        internal static string FailedGetInstructorId {
            get {
                return ResourceManager.GetString("FailedGetInstructorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load instructor&apos;s schedule.
        /// </summary>
        internal static string FailedLoadSchedule {
            get {
                return ResourceManager.GetString("FailedLoadSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load your driving skills progress. Please, try again later.
        /// </summary>
        internal static string FailedToLoadDrivingSkills {
            get {
                return ResourceManager.GetString("FailedToLoadDrivingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load instructor info.
        /// </summary>
        internal static string FailedToLoadInstuctor {
            get {
                return ResourceManager.GetString("FailedToLoadInstuctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while picking image from files. Try again later.
        /// </summary>
        internal static string FailedToPickImage {
            get {
                return ResourceManager.GetString("FailedToPickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update driving skill. Try again later.
        /// </summary>
        internal static string FailedToUpdateSkill {
            get {
                return ResourceManager.GetString("FailedToUpdateSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update profile photo.
        /// </summary>
        internal static string FailedUpdateUserPhoto {
            get {
                return ResourceManager.GetString("FailedUpdateUserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Sign up to instructor.
        /// </summary>
        internal static string FiledSignUpToInstructor {
            get {
                return ResourceManager.GetString("FiledSignUpToInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string FlyoutHeader_ChooseLanguage {
            get {
                return ResourceManager.GetString("FlyoutHeader_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        internal static string FlyoutHeader_Hello {
            get {
                return ResourceManager.GetString("FlyoutHeader_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ForgotPassword_Button {
            get {
                return ResourceManager.GetString("ForgotPassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string ForgotPassword_Head {
            get {
                return ResourceManager.GetString("ForgotPassword_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string ForgotPassword_Label {
            get {
                return ResourceManager.GetString("ForgotPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to schedule.
        /// </summary>
        internal static string GoToSchedule {
            get {
                return ResourceManager.GetString("GoToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivingCategory.
        /// </summary>
        internal static string InstructorCard_DrivingCategory {
            get {
                return ResourceManager.GetString("InstructorCard_DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string InstructorCard_Experience {
            get {
                return ResourceManager.GetString("InstructorCard_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiting.
        /// </summary>
        internal static string InstructorCard_Raiting {
            get {
                return ResourceManager.GetString("InstructorCard_Raiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string InstructorCard_Years {
            get {
                return ResourceManager.GetString("InstructorCard_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set rating to car.
        /// </summary>
        internal static string InstructorDetails_AddCarReview {
            get {
                return ResourceManager.GetString("InstructorDetails_AddCarReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        internal static string InstructorDetails_AddCommentButton {
            get {
                return ResourceManager.GetString("InstructorDetails_AddCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        internal static string InstructorDetails_AverageRating {
            get {
                return ResourceManager.GetString("InstructorDetails_AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car rating.
        /// </summary>
        internal static string InstructorDetails_AverageRatingCar {
            get {
                return ResourceManager.GetString("InstructorDetails_AverageRatingCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews about car.
        /// </summary>
        internal static string InstructorDetails_CarCommentsButton {
            get {
                return ResourceManager.GetString("InstructorDetails_CarCommentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture year.
        /// </summary>
        internal static string InstructorDetails_CarManufactureYear {
            get {
                return ResourceManager.GetString("InstructorDetails_CarManufactureYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car for learning.
        /// </summary>
        internal static string InstructorDetails_CarSectionTitle {
            get {
                return ResourceManager.GetString("InstructorDetails_CarSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Category.
        /// </summary>
        internal static string InstructorDetails_DrivingCategory {
            get {
                return ResourceManager.GetString("InstructorDetails_DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string InstructorDetails_Experience {
            get {
                return ResourceManager.GetString("InstructorDetails_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews about instructor.
        /// </summary>
        internal static string InstructorDetails_InstructorCommentsButton {
            get {
                return ResourceManager.GetString("InstructorDetails_InstructorCommentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main information about instructor.
        /// </summary>
        internal static string InstructorDetails_InstructorSectionTitle {
            get {
                return ResourceManager.GetString("InstructorDetails_InstructorSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of students .
        /// </summary>
        internal static string InstructorDetails_MaxNumberOfStudents {
            get {
                return ResourceManager.GetString("InstructorDetails_MaxNumberOfStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string InstructorDetails_MyProfile {
            get {
                return ResourceManager.GetString("InstructorDetails_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number ratings.
        /// </summary>
        internal static string InstructorDetails_NumberRatings {
            get {
                return ResourceManager.GetString("InstructorDetails_NumberRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to instructor.
        /// </summary>
        internal static string InstructorDetails_SignUpToInstructorButton {
            get {
                return ResourceManager.GetString("InstructorDetails_SignUpToInstructorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Details.
        /// </summary>
        internal static string InstructorDetails_Title {
            get {
                return ResourceManager.GetString("InstructorDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        internal static string InstructorDetails_Transmission {
            get {
                return ResourceManager.GetString("InstructorDetails_Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date:.
        /// </summary>
        internal static string InstructorReviews_DateCreatedlabel {
            get {
                return ResourceManager.GetString("InstructorReviews_DateCreatedlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my review.
        /// </summary>
        internal static string InstructorReviews_DeleteButton {
            get {
                return ResourceManager.GetString("InstructorReviews_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Review.
        /// </summary>
        internal static string InstructorReviews_MyReview {
            get {
                return ResourceManager.GetString("InstructorReviews.MyReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: .
        /// </summary>
        internal static string InstructorReviews_RatingLabel {
            get {
                return ResourceManager.GetString("InstructorReviews_RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review from.
        /// </summary>
        internal static string InstructorReviews_ReviewFrom {
            get {
                return ResourceManager.GetString("InstructorReviews_ReviewFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review: .
        /// </summary>
        internal static string InstructorReviews_ReviewLabel {
            get {
                return ResourceManager.GetString("InstructorReviews_ReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews about instructor.
        /// </summary>
        internal static string InstructorReviews_Title {
            get {
                return ResourceManager.GetString("InstructorReviews_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string InstructorSchedule_SingUp {
            get {
                return ResourceManager.GetString("InstructorSchedule_SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons schedule.
        /// </summary>
        internal static string InstructorScheduleStudent_Title {
            get {
                return ResourceManager.GetString("InstructorScheduleStudent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student profle.
        /// </summary>
        internal static string InstructorStudentProfile_StudentProfile {
            get {
                return ResourceManager.GetString("InstructorStudentProfile_StudentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email or password.
        /// </summary>
        internal static string InvalidCreds {
            get {
                return ResourceManager.GetString("InvalidCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct email address.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLease, enter a phone number in format: XXX-XXX-XXXX.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sign up.
        /// </summary>
        internal static string LessonSignUp_Confirm {
            get {
                return ResourceManager.GetString("LessonSignUp_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson date.
        /// </summary>
        internal static string LessonSignUp_Date {
            get {
                return ResourceManager.GetString("LessonSignUp_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Time.
        /// </summary>
        internal static string LessonSignUp_LessonTime {
            get {
                return ResourceManager.GetString("LessonSignUp_LessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To finish registration for lesson you need to pay for it. Please click on button bellow and pay through our web-site..
        /// </summary>
        internal static string LessonSignUp_NeedOpenBrowser {
            get {
                return ResourceManager.GetString("LessonSignUp_NeedOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string LessonSignUp_Price {
            get {
                return ResourceManager.GetString("LessonSignUp_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to lesson.
        /// </summary>
        internal static string LessonSignUp_SignUp {
            get {
                return ResourceManager.GetString("LessonSignUp_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        internal static string LoginGreetingText {
            get {
                return ResourceManager.GetString("LoginGreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My lessons.
        /// </summary>
        internal static string MyLessons_Title {
            get {
                return ResourceManager.GetString("MyLessons_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel lesson.
        /// </summary>
        internal static string MySchedule_CancelLesson {
            get {
                return ResourceManager.GetString("MySchedule_CancelLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed up student:.
        /// </summary>
        internal static string MySchedule_SignedUpStudent {
            get {
                return ResourceManager.GetString("MySchedule_SignedUpStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open student profile.
        /// </summary>
        internal static string MySchedule_ViewStudentProfile {
            get {
                return ResourceManager.GetString("MySchedule_ViewStudentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User?.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered passwords are not equal.
        /// </summary>
        internal static string NotEqualPasswords {
            get {
                return ResourceManager.GetString("NotEqualPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a valid email.
        /// </summary>
        internal static string nvalidEmail {
            get {
                return ResourceManager.GetString("nvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You request haven&apos;t being confirming by our administration. Please wait for some time.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category to learn.
        /// </summary>
        internal static string Registration_DrivingCaregoryLabel {
            get {
                return ResourceManager.GetString("Registration_DrivingCaregoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Registration_EmailLabel {
            get {
                return ResourceManager.GetString("Registration_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        internal static string Registration_EnterFirstName {
            get {
                return ResourceManager.GetString("Registration_EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string Registration_EnterLastName {
            get {
                return ResourceManager.GetString("Registration_EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Registration_PasswordLabel {
            get {
                return ResourceManager.GetString("Registration_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Registration_PhoneLabel {
            get {
                return ResourceManager.GetString("Registration_PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string Registration_RepeatPassword {
            get {
                return ResourceManager.GetString("Registration_RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration_Title {
            get {
                return ResourceManager.GetString("Registration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was rejected. You can send a request to our another instructor..
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rememeber me?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not send request to connect to instructor yet..
        /// </summary>
        internal static string RequestNotSent {
            get {
                return ResourceManager.GetString("RequestNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent you an email. Please, check your inbox or spam to reset your password.
        /// </summary>
        internal static string ResetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson already passed.
        /// </summary>
        internal static string Schedule_LessonPassed {
            get {
                return ResourceManager.GetString("Schedule_LessonPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My schedule.
        /// </summary>
        internal static string Schedule_MySchedule {
            get {
                return ResourceManager.GetString("Schedule_MySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string Schedule_NextWeek {
            get {
                return ResourceManager.GetString("Schedule_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        internal static string Schedule_PreviousWeek {
            get {
                return ResourceManager.GetString("Schedule_PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My chats.
        /// </summary>
        internal static string Shell_AllChats {
            get {
                return ResourceManager.GetString("Shell_AllChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All instructors.
        /// </summary>
        internal static string Shell_AllInstructors {
            get {
                return ResourceManager.GetString("Shell_AllInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My instructor.
        /// </summary>
        internal static string Shell_MyInstructor {
            get {
                return ResourceManager.GetString("Shell_MyInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My lessons.
        /// </summary>
        internal static string Shell_MyLessons {
            get {
                return ResourceManager.GetString("Shell_MyLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My schedule.
        /// </summary>
        internal static string Shell_MyScheduleInstructor {
            get {
                return ResourceManager.GetString("Shell_MyScheduleInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Shell_MyScheduleStudent {
            get {
                return ResourceManager.GetString("Shell_MyScheduleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string Shell_Profile {
            get {
                return ResourceManager.GetString("Shell_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with instructor.
        /// </summary>
        internal static string Shell_StudentChatMenuItem {
            get {
                return ResourceManager.GetString("Shell_StudentChatMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You request was successfully sent. Wait while administrators will confirm it.
        /// </summary>
        internal static string SignUpToInstructorSuccess {
            get {
                return ResourceManager.GetString("SignUpToInstructorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.\nTry again later or contact developer team.
        /// </summary>
        internal static string SomethingWentWrongErrorMessage {
            get {
                return ResourceManager.GetString("SomethingWentWrongErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Lesson.
        /// </summary>
        internal static string StudentMyLessons_CancelLesson {
            get {
                return ResourceManager.GetString("StudentMyLessons_CancelLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future lessons.
        /// </summary>
        internal static string StudentMyLessons_FutureLessons {
            get {
                return ResourceManager.GetString("StudentMyLessons_FutureLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have future lessons.
        /// </summary>
        internal static string StudentMyLessons_NoFutureLabel {
            get {
                return ResourceManager.GetString("StudentMyLessons_NoFutureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed lessons.
        /// </summary>
        internal static string StudentMyLessons_PassedLessons {
            get {
                return ResourceManager.GetString("StudentMyLessons_PassedLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can sign up to lesson in schedule.
        /// </summary>
        internal static string StudentMyLessons_SignUp {
            get {
                return ResourceManager.GetString("StudentMyLessons_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday date.
        /// </summary>
        internal static string StudentProfile_BirthdayDate {
            get {
                return ResourceManager.GetString("StudentProfile_BirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string StudentProfile_City {
            get {
                return ResourceManager.GetString("StudentProfile_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open full info.
        /// </summary>
        internal static string StudentProfile_DetailedInfo {
            get {
                return ResourceManager.GetString("StudentProfile_DetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category for learning.
        /// </summary>
        internal static string StudentProfile_DrivingCategory {
            get {
                return ResourceManager.GetString("StudentProfile_DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StudentProfile_Email {
            get {
                return ResourceManager.GetString("StudentProfile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string StudentProfile_FirstName {
            get {
                return ResourceManager.GetString("StudentProfile_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my lessons.
        /// </summary>
        internal static string StudentProfile_GoToLessonsButton {
            get {
                return ResourceManager.GetString("StudentProfile_GoToLessonsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Schedule.
        /// </summary>
        internal static string StudentProfile_GoToSchedule {
            get {
                return ResourceManager.GetString("StudentProfile_GoToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My instructor.
        /// </summary>
        internal static string StudentProfile_InstructorInfoTitle {
            get {
                return ResourceManager.GetString("StudentProfile_InstructorInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to instructor status.
        /// </summary>
        internal static string StudentProfile_InstructorRequestStatusTitle {
            get {
                return ResourceManager.GetString("StudentProfile_InstructorRequestStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string StudentProfile_LastName {
            get {
                return ResourceManager.GetString("StudentProfile_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed lessons.
        /// </summary>
        internal static string StudentProfile_LessonsStatisticTitle {
            get {
                return ResourceManager.GetString("StudentProfile_LessonsStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string StudentProfile_MainTitle {
            get {
                return ResourceManager.GetString("StudentProfile_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string StudentProfile_MyProfile {
            get {
                return ResourceManager.GetString("StudentProfile_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number learned driving skills:.
        /// </summary>
        internal static string StudentProfile_NumberLearnedExercises {
            get {
                return ResourceManager.GetString("StudentProfile_NumberLearnedExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number passed lessons:.
        /// </summary>
        internal static string StudentProfile_NumberLessonsLabel {
            get {
                return ResourceManager.GetString("StudentProfile_NumberLessonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View driving skills to learn.
        /// </summary>
        internal static string StudentProfile_OpenDrivingSkills {
            get {
                return ResourceManager.GetString("StudentProfile_OpenDrivingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        internal static string StudentProfile_PersonalTitle {
            get {
                return ResourceManager.GetString("StudentProfile_PersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string StudentProfile_PhoneNumber {
            get {
                return ResourceManager.GetString("StudentProfile_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of learned skills.
        /// </summary>
        internal static string StudentProfile_ProgressLabel {
            get {
                return ResourceManager.GetString("StudentProfile_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string StudentProfile_SendMessage {
            get {
                return ResourceManager.GetString("StudentProfile_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal info.
        /// </summary>
        internal static string StudentProfile_UpdateInfo {
            get {
                return ResourceManager.GetString("StudentProfile_UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string StudentProfile_UpdatePassword {
            get {
                return ResourceManager.GetString("StudentProfile_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string StudentProfile_UpdatePhoto {
            get {
                return ResourceManager.GetString("StudentProfile_UpdatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View instructors.
        /// </summary>
        internal static string StudentProfile_ViewInstructors {
            get {
                return ResourceManager.GetString("StudentProfile_ViewInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password update successsfully.
        /// </summary>
        internal static string SuccessPasswordUpdate {
            get {
                return ResourceManager.GetString("SuccessPasswordUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be elder than 18 to get access to driving license classes.
        /// </summary>
        internal static string TooYoungError {
            get {
                return ResourceManager.GetString("TooYoungError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string UpdatePassword_CancelButton {
            get {
                return ResourceManager.GetString("UpdatePassword_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string UpdatePassword_NewPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string UpdatePassword_NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UpdatePassword_NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        internal static string UpdatePassword_OldPassword {
            get {
                return ResourceManager.GetString("UpdatePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string UpdatePassword_OldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UpdatePassword_OldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string UpdatePassword_Title {
            get {
                return ResourceManager.GetString("UpdatePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdatePassword_UpdateButton {
            get {
                return ResourceManager.GetString("UpdatePassword_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter both current and new passwords..
        /// </summary>
        internal static string UpdatePasswordNotFilled {
            get {
                return ResourceManager.GetString("UpdatePasswordNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal info.
        /// </summary>
        internal static string UpdateStudent_Title {
            get {
                return ResourceManager.GetString("UpdateStudent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living address.
        /// </summary>
        internal static string UserProfile_Address {
            get {
                return ResourceManager.GetString("UserProfile_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category learning for:.
        /// </summary>
        internal static string UserProfile_DrivingCategory {
            get {
                return ResourceManager.GetString("UserProfile_DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor info.
        /// </summary>
        internal static string UserProfile_InstructiorInfo {
            get {
                return ResourceManager.GetString("UserProfile_InstructiorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons statistic.
        /// </summary>
        internal static string UserProfile_LessonsStatistic {
            get {
                return ResourceManager.GetString("UserProfile_LessonsStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
