//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto.School.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auto.School.Mobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile photo.
        /// </summary>
        internal static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open details.
        /// </summary>
        internal static string AllInstructors_DetailsButton {
            get {
                return ResourceManager.GetString("AllInstructors.DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor has maximum number of students.
        /// </summary>
        internal static string AllInstructors_NotAvailale {
            get {
                return ResourceManager.GetString("AllInstructors.NotAvailale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Instructors.
        /// </summary>
        internal static string AllInstructors_Title {
            get {
                return ResourceManager.GetString("AllInstructors.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        internal static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string BirthdayDate {
            get {
                return ResourceManager.GetString("BirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DrivingSkills_Completed {
            get {
                return ResourceManager.GetString("DrivingSkills.Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark completed.
        /// </summary>
        internal static string DrivingSkills_MarkCompleted {
            get {
                return ResourceManager.GetString("DrivingSkills.MarkCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving skills to learn.
        /// </summary>
        internal static string DrivingSkills_Title {
            get {
                return ResourceManager.GetString("DrivingSkills.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ForgotPassword_Button {
            get {
                return ResourceManager.GetString("ForgotPassword.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string ForgotPassword_Head {
            get {
                return ResourceManager.GetString("ForgotPassword.Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string ForgotPassword_Label {
            get {
                return ResourceManager.GetString("ForgotPassword.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to schedule.
        /// </summary>
        internal static string GoToSchedule {
            get {
                return ResourceManager.GetString("GoToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivingCategory.
        /// </summary>
        internal static string InstructorCard_DrivingCategory {
            get {
                return ResourceManager.GetString("InstructorCard.DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string InstructorCard_Experience {
            get {
                return ResourceManager.GetString("InstructorCard.Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiting.
        /// </summary>
        internal static string InstructorCard_Raiting {
            get {
                return ResourceManager.GetString("InstructorCard.Raiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string InstructorCard_Years {
            get {
                return ResourceManager.GetString("InstructorCard.Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews about car.
        /// </summary>
        internal static string InstructorDetails_CarCommentsButton {
            get {
                return ResourceManager.GetString("InstructorDetails.CarCommentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car for learning.
        /// </summary>
        internal static string InstructorDetails_CarSectionTitle {
            get {
                return ResourceManager.GetString("InstructorDetails.CarSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews about instructor.
        /// </summary>
        internal static string InstructorDetails_InstructorCommentsButton {
            get {
                return ResourceManager.GetString("InstructorDetails.InstructorCommentsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main information about instructor.
        /// </summary>
        internal static string InstructorDetails_InstructorSectionTitle {
            get {
                return ResourceManager.GetString("InstructorDetails.InstructorSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to instructor.
        /// </summary>
        internal static string InstructorDetails_SignUpToInstructorButton {
            get {
                return ResourceManager.GetString("InstructorDetails.SignUpToInstructorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Details.
        /// </summary>
        internal static string InstructorDetails_Title {
            get {
                return ResourceManager.GetString("InstructorDetails.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string InstructorSchedule_SingUp {
            get {
                return ResourceManager.GetString("InstructorSchedule.SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sign up.
        /// </summary>
        internal static string LessonSignUp_Confirm {
            get {
                return ResourceManager.GetString("LessonSignUp.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson date.
        /// </summary>
        internal static string LessonSignUp_Date {
            get {
                return ResourceManager.GetString("LessonSignUp.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Time.
        /// </summary>
        internal static string LessonSignUp_LessonTime {
            get {
                return ResourceManager.GetString("LessonSignUp.LessonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string LessonSignUp_Price {
            get {
                return ResourceManager.GetString("LessonSignUp.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to lesson.
        /// </summary>
        internal static string LessonSignUp_SignUp {
            get {
                return ResourceManager.GetString("LessonSignUp.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        internal static string LoginGreetingText {
            get {
                return ResourceManager.GetString("LoginGreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User?.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category to learn.
        /// </summary>
        internal static string Registration_DrivingCaregoryLabel {
            get {
                return ResourceManager.GetString("Registration.DrivingCaregoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Registration_EmailLabel {
            get {
                return ResourceManager.GetString("Registration.EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        internal static string Registration_EnterFirstName {
            get {
                return ResourceManager.GetString("Registration.EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string Registration_EnterLastName {
            get {
                return ResourceManager.GetString("Registration.EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Registration_PasswordLabel {
            get {
                return ResourceManager.GetString("Registration.PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Registration_PhoneLabel {
            get {
                return ResourceManager.GetString("Registration.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string Registration_RepeatPassword {
            get {
                return ResourceManager.GetString("Registration.RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rememeber me?.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string Schedule_NextWeek {
            get {
                return ResourceManager.GetString("Schedule.NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        internal static string Schedule_PreviousWeek {
            get {
                return ResourceManager.GetString("Schedule.PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your city.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future lessons.
        /// </summary>
        internal static string StudentMyLessons_FutureLessons {
            get {
                return ResourceManager.GetString("StudentMyLessons.FutureLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have future lessons.
        /// </summary>
        internal static string StudentMyLessons_NoFutureLabel {
            get {
                return ResourceManager.GetString("StudentMyLessons.NoFutureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed lessons.
        /// </summary>
        internal static string StudentMyLessons_PassedLessons {
            get {
                return ResourceManager.GetString("StudentMyLessons.PassedLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can sign up to lesson in schedule.
        /// </summary>
        internal static string StudentMyLessons_SignUp {
            get {
                return ResourceManager.GetString("StudentMyLessons.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday date.
        /// </summary>
        internal static string StudentProfile_BirthdayDate {
            get {
                return ResourceManager.GetString("StudentProfile.BirthdayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string StudentProfile_City {
            get {
                return ResourceManager.GetString("StudentProfile.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open full info.
        /// </summary>
        internal static string StudentProfile_DetailedInfo {
            get {
                return ResourceManager.GetString("StudentProfile.DetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category for learning.
        /// </summary>
        internal static string StudentProfile_DrivingCategory {
            get {
                return ResourceManager.GetString("StudentProfile.DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StudentProfile_Email {
            get {
                return ResourceManager.GetString("StudentProfile.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string StudentProfile_FirstName {
            get {
                return ResourceManager.GetString("StudentProfile.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View my lessons.
        /// </summary>
        internal static string StudentProfile_GoToLessonsButton {
            get {
                return ResourceManager.GetString("StudentProfile.GoToLessonsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Schedule.
        /// </summary>
        internal static string StudentProfile_GoToSchedule {
            get {
                return ResourceManager.GetString("StudentProfile.GoToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My instructor.
        /// </summary>
        internal static string StudentProfile_InstructorInfoTitle {
            get {
                return ResourceManager.GetString("StudentProfile.InstructorInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to instructor status.
        /// </summary>
        internal static string StudentProfile_InstructorRequestStatusTitle {
            get {
                return ResourceManager.GetString("StudentProfile.InstructorRequestStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string StudentProfile_LastName {
            get {
                return ResourceManager.GetString("StudentProfile.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed lessons.
        /// </summary>
        internal static string StudentProfile_LessonsStatisticTitle {
            get {
                return ResourceManager.GetString("StudentProfile.LessonsStatisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string StudentProfile_MainTitle {
            get {
                return ResourceManager.GetString("StudentProfile.MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number learned driving skills:.
        /// </summary>
        internal static string StudentProfile_NumberLearnedExercises {
            get {
                return ResourceManager.GetString("StudentProfile.NumberLearnedExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number passed lessons:.
        /// </summary>
        internal static string StudentProfile_NumberLessonsLabel {
            get {
                return ResourceManager.GetString("StudentProfile.NumberLessonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View driving skills to learn.
        /// </summary>
        internal static string StudentProfile_OpenDrivingSkills {
            get {
                return ResourceManager.GetString("StudentProfile.OpenDrivingSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        internal static string StudentProfile_PersonalTitle {
            get {
                return ResourceManager.GetString("StudentProfile.PersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string StudentProfile_PhoneNumber {
            get {
                return ResourceManager.GetString("StudentProfile.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of learned skills.
        /// </summary>
        internal static string StudentProfile_ProgressLabel {
            get {
                return ResourceManager.GetString("StudentProfile.ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string StudentProfile_SendMessage {
            get {
                return ResourceManager.GetString("StudentProfile.SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal info.
        /// </summary>
        internal static string StudentProfile_UpdateInfo {
            get {
                return ResourceManager.GetString("StudentProfile.UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string StudentProfile_UpdatePassword {
            get {
                return ResourceManager.GetString("StudentProfile.UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string StudentProfile_UpdatePhoto {
            get {
                return ResourceManager.GetString("StudentProfile.UpdatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View instructors.
        /// </summary>
        internal static string StudentProfile_ViewInstructors {
            get {
                return ResourceManager.GetString("StudentProfile.ViewInstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UpdatePassword_CancelButton {
            get {
                return ResourceManager.GetString("UpdatePassword.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        internal static string UpdatePassword_NewPassword {
            get {
                return ResourceManager.GetString("UpdatePassword.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string UpdatePassword_NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UpdatePassword.NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        internal static string UpdatePassword_OldPassword {
            get {
                return ResourceManager.GetString("UpdatePassword.OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string UpdatePassword_OldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UpdatePassword.OldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string UpdatePassword_Title {
            get {
                return ResourceManager.GetString("UpdatePassword.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdatePassword_UpdateButton {
            get {
                return ResourceManager.GetString("UpdatePassword.UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal info.
        /// </summary>
        internal static string UpdateStudent_Title {
            get {
                return ResourceManager.GetString("UpdateStudent.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living address.
        /// </summary>
        internal static string UserProfile_Address {
            get {
                return ResourceManager.GetString("UserProfile.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving category learning for:.
        /// </summary>
        internal static string UserProfile_DrivingCategory {
            get {
                return ResourceManager.GetString("UserProfile.DrivingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor info.
        /// </summary>
        internal static string UserProfile_InstructiorInfo {
            get {
                return ResourceManager.GetString("UserProfile.InstructiorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons statistic.
        /// </summary>
        internal static string UserProfile_LessonsStatistic {
            get {
                return ResourceManager.GetString("UserProfile.LessonsStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
