name: CI for .NET MAUI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code.github/workflows/auto-school-server/ci.yml
        uses: actions/checkout@v2

    - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
        dotnet-version: '8.0.x'

    - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODE_COV_TOKEN }}
          slug: IhorPanasenko/AutoSchool

    - name: Restore dependencies
        run: dotnet restore

    - name: Build project
        run: dotnet build

    # - name: Run tests
    #     run: dotnet test


